apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
  namespace: oauth2-proxy
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-shared
  target:
    name: oauth2-proxy-secrets
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: AUTH0_CLIENT_ID_OAUTH2_PROXY
    - secretKey: client-secret
      remoteRef:
        key: AUTH0_CLIENT_SECRET_OAUTH2_PROXY
    - secretKey: cookie-secret
      remoteRef:
        key: OAUTH2_PROXY_COOKIE_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth0-issuer
  namespace: oauth2-proxy
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-shared
  target:
    name: auth0-issuer
    creationPolicy: Owner
    template:
      data:
        issuer-url: "https://{{ .domain }}/"
        logout-url: "https://{{ .domain }}/v2/logout"
  data:
    - secretKey: domain
      remoteRef:
        key: AUTH0_DOMAIN
