apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
  namespace: oauth2-proxy
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-shared
  target:
    name: oauth2-proxy-secrets
    creationPolicy: Owner
    template:
      data:
        client-id: {{ .Values.global.auth0.clientId | quote }}
        client-secret: "{{`{{ .clientSecret }}`}}"
        cookie-secret: "{{`{{ .cookieSecret }}`}}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: AUTH0_CLIENT_SECRET
    - secretKey: cookieSecret
      remoteRef:
        key: OAUTH2_PROXY_COOKIE_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-redis
  namespace: oauth2-proxy
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-shared
  target:
    name: oauth2-proxy-redis
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: OAUTH2_PROXY_REDIS_PASSWORD
