{{- range $name, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  namespace: {{ $service.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: {{ $.Values.oauth2Proxy.authUrl | quote }}
    nginx.ingress.kubernetes.io/auth-signin: {{ $.Values.oauth2Proxy.authSignin | quote }}
    nginx.ingress.kubernetes.io/auth-response-headers: {{ $.Values.oauth2Proxy.authResponseHeaders | quote }}
    {{- if $service.backend.protocol }}
    nginx.ingress.kubernetes.io/backend-protocol: {{ $service.backend.protocol | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/server-snippet: |
      location = /logout {
        return 302 /oauth2/sign_out?rd=https%3A%2F%2F{{ $.Values.oauth2Proxy.auth0Domain }}%2Fv2%2Flogout%3Fclient_id%3D{{ $.Values.oauth2Proxy.auth0ClientId }}%26returnTo%3Dhttps%253A%252F%252F$host;
      }
spec:
  ingressClassName: nginx
  rules:
    - host: {{ $name }}.{{ $.Values.tailnet }}.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $service.backend.name }}
                port:
                  number: {{ $service.backend.port }}
{{- end }}
{{- end }}
