{{- range $name, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  namespace: {{ $service.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: {{ $.Values.oauth2Proxy.authUrl | quote }}
    nginx.ingress.kubernetes.io/auth-signin: {{ $.Values.oauth2Proxy.authSignin | quote }}
    nginx.ingress.kubernetes.io/auth-response-headers: {{ $.Values.oauth2Proxy.authResponseHeaders | quote }}
    {{- if $service.backend.protocol }}
    nginx.ingress.kubernetes.io/backend-protocol: {{ $service.backend.protocol | quote }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ $name }}.{{ $.Values.tailnet }}.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $service.backend.name }}
                port:
                  number: {{ $service.backend.port }}
{{- end }}
{{- end }}
