{{- range $name, $service := .Values.services }}
{{- if and $service.enabled (not $service.hostname) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}-tailscale
  namespace: ingress-nginx
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - {{ $name }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-ingress-ingress-nginx-controller
                port:
                  number: 80
{{- end }}
{{- end }}
